# Site settings
author: Wendy Calderon
title: Wendy's Notes
header-img: img/home-bg.png
email: wendycalderon@gmail.com
copyright_name: Wendy Calderon
description: > # this means to ignore newlines until "baseurl:"
  New career, new mentality, new opportunities...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: wendisha
github_username:  wendisha

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
