# Site settings
title: 
header-img: img/home-bg.png
email: wendycalderon@gmail.com
copyright_name: wendisha
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: wendisha
github_username:  wendisha
learn_profile: wendisha
email_username: wendycalderon@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
